language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
  

deploy:
  provider: releases
  api_key:
    secure: 93174aa68ee5bfc5b6568a2199755eedc72b9939 
  file: sample/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
  	repo: Sherchen/Transitions-Everywhere
    tags: true
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_29be78bfd909_key -iv $encrypted_29be78bfd909_iv
  -in sherchen20170602.keystore.enc -out sherchen20170602.keystore -d
- gem install fir-cli
