language: android
android:
  components:
  - build-tools-23.0.2
  - android-23
#  - extra-google-google_play_services
#  - extra-google-m2repository
  - extra-android-m2repository
#  - addon-google_apis-google-19
#  - sys-img-armeabi-v7a-android-19
#  - sys-img-x86-android-17

rvm:
  -2.2

script:
- ./gradlew :sample:assembleRelease

before_install:
#- gem install fir-cli
- openssl aes-256-cbc -K $encrypted_29be78bfd909_key -iv $encrypted_29be78bfd909_iv
  -in sherchen20170602.keystore.enc -out sherchen20170602.keystore -d

deploy:
  provider: releases
  api_key:
    secure: 93174aa68ee5bfc5b6568a2199755eedc72b9939 
  file: sample/build/outputs/apk/sample-release.apk
  skip_cleanup: true
  on:
      repo: sherchen/Transitions-Everywhere
      tags: true
      all_branches: true

after_deploy:
- fir p sample/build/outputs/apk/sample-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"

