language: android
jdk: oraclejdk8
sudo: true

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.3
  - android-25
  - extra
script:
- "./gradlew :sample:assembleRelease"
#- "./gradlew publishApkRelease"
deploy:
  provider: releases
  api_key:
    secure: 93174aa68ee5bfc5b6568a2199755eedc72b9939
  file: sample/build/outputs/apk/sample-release.apk
  skip_cleanup: true
  on:
    repo: sherchen/Transitions-Everywhere
    tags: true
    all_branches: true
before_install:
- chmod a+x gradlew
- rvm install 2.1.5
- gem install fir-cli
#- openssl aes-256-cbc -K $encrypted_29be78bfd909_key -iv $encrypted_29be78bfd909_iv
#  -in sherchen20170602.keystore.enc -out sherchen20170602.keystore -d
after_deploy:
- fir p sample/build/outputs/apk/sample-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"