language: android
android:
  components:
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
script:
- "./gradlew :sample:assembleRelease"
- "./gradlew publishApkRelease"
deploy:
  provider: releases
  api_key:
    secure: 93174aa68ee5bfc5b6568a2199755eedc72b9939
  file: sample/build/outputs/apk/sample-release.apk
  skip_cleanup: true
  on:
    repo: sherchen/Transitions-Everywhere
    tags: true
    all_branches: true
before_install:
- chmod a+x gradlew
#- openssl aes-256-cbc -K $encrypted_29be78bfd909_key -iv $encrypted_29be78bfd909_iv
#  -in sherchen20170602.keystore.enc -out sherchen20170602.keystore -d
